jenkins_http_port: 8080
jenkins_key_url: https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
jenkins_repo: deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/